# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/mnt/data/NYU Notes/PROJECTS/CPP Server"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/mnt/data/NYU Notes/PROJECTS/CPP Server"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/mnt/data/NYU Notes/PROJECTS/CPP Server/CMakeFiles" "/mnt/data/NYU Notes/PROJECTS/CPP Server//CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/mnt/data/NYU Notes/PROJECTS/CPP Server/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named serve

# Build rule for target.
serve: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 serve
.PHONY : serve

# fast build rule for target.
serve/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serve.dir/build.make CMakeFiles/serve.dir/build
.PHONY : serve/fast

networking/requests/GET/get.o: networking/requests/GET/get.cpp.o
.PHONY : networking/requests/GET/get.o

# target to build an object file
networking/requests/GET/get.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serve.dir/build.make CMakeFiles/serve.dir/networking/requests/GET/get.cpp.o
.PHONY : networking/requests/GET/get.cpp.o

networking/requests/GET/get.i: networking/requests/GET/get.cpp.i
.PHONY : networking/requests/GET/get.i

# target to preprocess a source file
networking/requests/GET/get.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serve.dir/build.make CMakeFiles/serve.dir/networking/requests/GET/get.cpp.i
.PHONY : networking/requests/GET/get.cpp.i

networking/requests/GET/get.s: networking/requests/GET/get.cpp.s
.PHONY : networking/requests/GET/get.s

# target to generate assembly for a file
networking/requests/GET/get.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serve.dir/build.make CMakeFiles/serve.dir/networking/requests/GET/get.cpp.s
.PHONY : networking/requests/GET/get.cpp.s

networking/server/createServer.o: networking/server/createServer.cpp.o
.PHONY : networking/server/createServer.o

# target to build an object file
networking/server/createServer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serve.dir/build.make CMakeFiles/serve.dir/networking/server/createServer.cpp.o
.PHONY : networking/server/createServer.cpp.o

networking/server/createServer.i: networking/server/createServer.cpp.i
.PHONY : networking/server/createServer.i

# target to preprocess a source file
networking/server/createServer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serve.dir/build.make CMakeFiles/serve.dir/networking/server/createServer.cpp.i
.PHONY : networking/server/createServer.cpp.i

networking/server/createServer.s: networking/server/createServer.cpp.s
.PHONY : networking/server/createServer.s

# target to generate assembly for a file
networking/server/createServer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serve.dir/build.make CMakeFiles/serve.dir/networking/server/createServer.cpp.s
.PHONY : networking/server/createServer.cpp.s

networking/sockets/bindingSocket.o: networking/sockets/bindingSocket.cpp.o
.PHONY : networking/sockets/bindingSocket.o

# target to build an object file
networking/sockets/bindingSocket.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serve.dir/build.make CMakeFiles/serve.dir/networking/sockets/bindingSocket.cpp.o
.PHONY : networking/sockets/bindingSocket.cpp.o

networking/sockets/bindingSocket.i: networking/sockets/bindingSocket.cpp.i
.PHONY : networking/sockets/bindingSocket.i

# target to preprocess a source file
networking/sockets/bindingSocket.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serve.dir/build.make CMakeFiles/serve.dir/networking/sockets/bindingSocket.cpp.i
.PHONY : networking/sockets/bindingSocket.cpp.i

networking/sockets/bindingSocket.s: networking/sockets/bindingSocket.cpp.s
.PHONY : networking/sockets/bindingSocket.s

# target to generate assembly for a file
networking/sockets/bindingSocket.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serve.dir/build.make CMakeFiles/serve.dir/networking/sockets/bindingSocket.cpp.s
.PHONY : networking/sockets/bindingSocket.cpp.s

networking/sockets/createSocket.o: networking/sockets/createSocket.cpp.o
.PHONY : networking/sockets/createSocket.o

# target to build an object file
networking/sockets/createSocket.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serve.dir/build.make CMakeFiles/serve.dir/networking/sockets/createSocket.cpp.o
.PHONY : networking/sockets/createSocket.cpp.o

networking/sockets/createSocket.i: networking/sockets/createSocket.cpp.i
.PHONY : networking/sockets/createSocket.i

# target to preprocess a source file
networking/sockets/createSocket.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serve.dir/build.make CMakeFiles/serve.dir/networking/sockets/createSocket.cpp.i
.PHONY : networking/sockets/createSocket.cpp.i

networking/sockets/createSocket.s: networking/sockets/createSocket.cpp.s
.PHONY : networking/sockets/createSocket.s

# target to generate assembly for a file
networking/sockets/createSocket.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serve.dir/build.make CMakeFiles/serve.dir/networking/sockets/createSocket.cpp.s
.PHONY : networking/sockets/createSocket.cpp.s

networking/sockets/listeningSocket.o: networking/sockets/listeningSocket.cpp.o
.PHONY : networking/sockets/listeningSocket.o

# target to build an object file
networking/sockets/listeningSocket.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serve.dir/build.make CMakeFiles/serve.dir/networking/sockets/listeningSocket.cpp.o
.PHONY : networking/sockets/listeningSocket.cpp.o

networking/sockets/listeningSocket.i: networking/sockets/listeningSocket.cpp.i
.PHONY : networking/sockets/listeningSocket.i

# target to preprocess a source file
networking/sockets/listeningSocket.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serve.dir/build.make CMakeFiles/serve.dir/networking/sockets/listeningSocket.cpp.i
.PHONY : networking/sockets/listeningSocket.cpp.i

networking/sockets/listeningSocket.s: networking/sockets/listeningSocket.cpp.s
.PHONY : networking/sockets/listeningSocket.s

# target to generate assembly for a file
networking/sockets/listeningSocket.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serve.dir/build.make CMakeFiles/serve.dir/networking/sockets/listeningSocket.cpp.s
.PHONY : networking/sockets/listeningSocket.cpp.s

server.o: server.cpp.o
.PHONY : server.o

# target to build an object file
server.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serve.dir/build.make CMakeFiles/serve.dir/server.cpp.o
.PHONY : server.cpp.o

server.i: server.cpp.i
.PHONY : server.i

# target to preprocess a source file
server.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serve.dir/build.make CMakeFiles/serve.dir/server.cpp.i
.PHONY : server.cpp.i

server.s: server.cpp.s
.PHONY : server.s

# target to generate assembly for a file
server.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serve.dir/build.make CMakeFiles/serve.dir/server.cpp.s
.PHONY : server.cpp.s

startServer.o: startServer.cpp.o
.PHONY : startServer.o

# target to build an object file
startServer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serve.dir/build.make CMakeFiles/serve.dir/startServer.cpp.o
.PHONY : startServer.cpp.o

startServer.i: startServer.cpp.i
.PHONY : startServer.i

# target to preprocess a source file
startServer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serve.dir/build.make CMakeFiles/serve.dir/startServer.cpp.i
.PHONY : startServer.cpp.i

startServer.s: startServer.cpp.s
.PHONY : startServer.s

# target to generate assembly for a file
startServer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serve.dir/build.make CMakeFiles/serve.dir/startServer.cpp.s
.PHONY : startServer.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... serve"
	@echo "... networking/requests/GET/get.o"
	@echo "... networking/requests/GET/get.i"
	@echo "... networking/requests/GET/get.s"
	@echo "... networking/server/createServer.o"
	@echo "... networking/server/createServer.i"
	@echo "... networking/server/createServer.s"
	@echo "... networking/sockets/bindingSocket.o"
	@echo "... networking/sockets/bindingSocket.i"
	@echo "... networking/sockets/bindingSocket.s"
	@echo "... networking/sockets/createSocket.o"
	@echo "... networking/sockets/createSocket.i"
	@echo "... networking/sockets/createSocket.s"
	@echo "... networking/sockets/listeningSocket.o"
	@echo "... networking/sockets/listeningSocket.i"
	@echo "... networking/sockets/listeningSocket.s"
	@echo "... server.o"
	@echo "... server.i"
	@echo "... server.s"
	@echo "... startServer.o"
	@echo "... startServer.i"
	@echo "... startServer.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

